services:
  nodejs-aws-cart-api:
    env_file:
      - .env
    build:
      context: .
      target: production
      args:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DATABASE=${DB_DATABASE}
    ports:
      - '5000:5000'
    volumes:
      - ./src:/usr/src/app
